Testing
milen-ale/todo-list-testing pull request #1
Opened 2022-07-28 13:07 UTC by milen-ale

This is a simple todo list web page built using Webpack and served by a Webpack dev server. It features the CRUD operations.
- Data is stored in localStorage
-. Has some automated tests written using Jest.

2022-07-28 14:07 UTC, codepantha approved these changes
# STATUS: APPROVED 🟢 🍷 

## Hi team 👋, 

You have done an amazing job 👏 
Your project is now complete, and there is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Highlights ⭐ 
✔️ Descriptive PR
✔️ Tests have been written for adding and deleting to-do items
✔️ Good commit history
✔️ No linter errors

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-28 15:15 UTC, arslanbisharat requested changes
Hi @milen-ale, @codepantha, and @MxoDevops, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- The Pull Request has a proper title and description. ✔️
- You have added a descriptive Readme file. Good Job. ✔️
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [x] Please make sure you right descriptive comments. Commenting involves placing Human Readable Descriptions inside of computer programs detailing what the Code is doing. Proper use of commenting can make code maintenance much easier, as well as helping make finding bugs faster. Further, commenting is very important when writing functions that other people will use. :x:


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-28 15:15 UTC, arslanbisharat commented on src/crudOps.test.js
> +/* eslint-disable */
- [ ] Please make sure all the linter rules are enabled. These are here to help us write clean code.

2022-07-28 15:15 UTC, arslanbisharat commented on src/index.js
> +/* eslint-disable */
- [x] Please make sure all the linter rules are enabled. These are here to help us write clean code.

2022-07-28 15:15 UTC, arslanbisharat commented on webpack.config.js
> +/* eslint-disable */
- [ ] Please make sure all the linter rules are enabled. These are here to help us write clean code.

2022-07-29 07:56 UTC, KDlamini approved these changes
### Hi team @milen-ale, @MxoDevops 🙋‍♀️

Excellent work! 💯 
You have done a great job implementing all the required changes. 
Your feature is complete! There is nothing else to say other than... it's time to merge it. :shipit: 
Congratulations!!!🎊 🥳 

## Highlights 🌞 
✔️  Add and remove methods are tested
✔️  No linter errors

# Status: Approved ✔️ 

![giphyapproved](https://user-images.githubusercontent.com/38088818/152676874-3b2edc2c-a46f-4da6-b253-be859d2a2c65.gif)
 
Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-29 11:38 UTC, merged